//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilestoneReportDAL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MilestoneReportResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MilestoneReportResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MilestoneReportDAL.MilestoneReportResource", typeof(MilestoneReportResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select  mc.ID_MS_CAT, mc.MS_CAT_NAME, mc.MS_CAT_ORD, 
        ///        mil.ID_MILESTONE, mil.MILESTONE_NAME, mil.ID_MSP, mil.Ord, 
        ///        prmil.FACT_DATE, prmil.USER_NAME
        ///from PROJ_MILESTONE prmil
        ///left join milestone mil on mil.id_milestone = prmil.id_milestone
        ///left join milestone_category mc on MIL.ID_MS_CAT= MC.ID_MS_CAT
        ///where ID_PROJ in (select ID_PROJECT from PROJECT where DOGOVOR = :DOGOVOR and DC = :DC)
        ///order by mc.MS_CAT_ORD, mil.Ord.
        /// </summary>
        internal static string GetMilestoneForDogovorSqlReqest {
            get {
                return ResourceManager.GetString("GetMilestoneForDogovorSqlReqest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select  mc.ID_MS_CAT, mc.MS_CAT_NAME, mc.MS_CAT_ORD, 
        ///        mil.ID_MILESTONE, mil.MILESTONE_NAME, mil.ID_MSP, mil.Ord
        ///from milestone mil
        ///left join milestone_category mc on MIL.ID_MS_CAT= MC.ID_MS_CAT
        ///order by mc.MS_CAT_ORD, mil.Ord.
        /// </summary>
        internal static string GetMilestoneFullListSqlReqest {
            get {
                return ResourceManager.GetString("GetMilestoneFullListSqlReqest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select [TaskStartDate], [TaskFinishDate], [Тип контрольной точки] 
        ///from [MSP_EpmTask_UserView]
        ///where [Тип контрольной точки] = CONVERT(NVARCHAR(MAX), (select [MemberFullValue]
        ///														from [MSPLT_Типы контрольных точек проекта_UserView] 
        ///														where [LookupMemberUID] = @ID_MSP)).
        /// </summary>
        internal static string GetMilestouneDateSqlRequest {
            get {
                return ResourceManager.GetString("GetMilestouneDateSqlRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select distinct dog.[TEXT_VALUE] as dog,
        ///                                           isnull(dc.[TEXT_VALUE], 0) as dc,
        ///                                           proj.[PROJ_CREATION_DATE] as creat_date,
        ///                                           publ.[Статус проекта] as status,
        ///	                                       (SELECT count(*)
        ///		                                    FROM [GPIProjectServer_Draft].[dbo].[MSP_TASK_CUSTOM_FIELD_VALUES] works
        ///		                                    where [MD_PROP_ID] in  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IsExistsInMsProjectSqlRequest {
            get {
                return ResourceManager.GetString("IsExistsInMsProjectSqlRequest", resourceCulture);
            }
        }
    }
}
